version: '3.1'

services:
  theengsgateway:
    image: theengs/gateway:latest
    network_mode: host
    environment:
      MQTT_HOST: 192.168.0.200
      MQTT_USERNAME: username
      MQTT_PASSWORD: ubersecretpassword
      MQTT_PUB_TOPIC: home/TheengsGateway/BTtoMQTT
      MQTT_SUB_TOPIC: home/+/BTtoMQTT/undecoded
      MQTT_PRE_TOPIC: home/presence/TheengsGateway
      PRESENCE: false
      PUBLISH_ALL: true
      TIME_BETWEEN: 60
      SCAN_TIME: 5
      LOG_LEVEL: DEBUG
      DISCOVERY: true
      HASS_DISCOVERY: true
      DISCOVERY_TOPIC: homeassistant/sensor
      DISCOVERY_DEVICE_NAME: TheengsGateway
      DISCOVERY_FILTER: "[IBEACON,GAEN,MS-CDP]"
      SCANNING_MODE: active
      ADAPTER: hci0
    volumes:
      - /var/run/dbus:/var/run/dbus
